<?xml version="1.0"?>
<!DOCTYPE book[
<!ELEMENT book(id,name,noofpages,author,price)>
<!ELEMENT id(#PCDATA)>
<!ELEMENT name(#PCDATA)>
<!ELEMENT noofpages(#PCADATA)>
<!ELEMENT author(#PCDATA)>
<!ELEMENT price(#PCDATA)>
]>
<book>
  <id>1271</id>
  <name>Gayathri</name>
  <noofpages>40</noofpages>
  <author>SatyaNarayana</author>
  <price>400</price>
</book>  